controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    methods: [ "GET" ]
    controller: App\Controller\AddTeachrController::index

addTeachr:
    path: /add_teachr
    methods: [ "GET", "POST" ]
    controller: App\Controller\AddTeachrController::addTeachr

editTeachr:
    path: /edit_teachr/{id}
    methods: [ "GET", "POST" ]
    controller: App\Controller\AddTeachrController::editTeachr

deleteTeachr:
    path: /delete_teachr/{id}
    methods: [ "GET", "POST" ]
    controller: App\Controller\AddTeachrController::deleteTeachr
